apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: slurm-poc
  name: controller-spool
spec:
  storageClassName: local-pv
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteMany
