apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "slurm-cluster-storage.volume.controller-spool.pv" . }}
spec:
  storageClassName: {{ include "slurm-cluster-storage.volume.controller-spool.storageClass" . }}
  volumeMode: Filesystem
  mountOptions:
    - rw
    - relatime
  capacity:
    storage: {{ include "slurm-cluster-storage.volume.controller-spool.size" . }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/controller-spool
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ include "slurm-cluster-storage.volume.controller-spool.pvc" . }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
{{ .Values.scheduling.cpuOnly.matchExpressions | toYaml | indent 12 }}
