{{- if eq (include "slurm-cluster-storage.volume.jail.type" .) "filestore" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "slurm-cluster-storage.volume.jail.mount" . }}
spec:
  selector:
    matchLabels:
      slurm: {{ include "slurm-cluster-storage.volume.jail.mount" . }}
  template:
    metadata:
      labels:
        slurm: {{ include "slurm-cluster-storage.volume.jail.mount" . }}
    spec:
      containers:
        - name: mount-jail-filestore
          image: busybox
          command:
            - /bin/sh
            - -c
            - /mount-scripts/ensure_mounted_filestore.sh -d {{ include "slurm-cluster-storage.volume.jail.device" . }} -p /mnt/jail -s 60
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-mount
              mountPath: /host/mnt
              mountPropagation: Bidirectional
            - name: mount-scripts
              mountPath: /mount-scripts
      volumes:
        - name: host-mount
          hostPath:
            path: /mnt
        - name: mount-scripts
          configMap:
            name: mount-scripts
            defaultMode: 0500
      tolerations:
        # Allow scheduling on GPU nodes
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              # Require scheduling on GPU nodes
              - matchExpressions:
                  - key: nebius.com/node-group-id
                    operator: In
                    values:
                      - {{ include "slurm-cluster-storage.nodeGroup.gpu" . }}
                      # Require scheduling on Non-GPU nodes
              - matchExpressions:
                  - key: nebius.com/node-group-id
                    operator: In
                    values:
                      - {{ include "slurm-cluster-storage.nodeGroup.nonGpu" . }}
{{- else if eq (include "slurm-cluster-storage.volume.jail.type" .) "glusterfs" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "slurm-cluster-storage.volume.jail.mount" . }}
spec:
  selector:
    matchLabels:
      slurm: {{ include "slurm-cluster-storage.volume.jail.mount" . }}
  template:
    metadata:
      labels:
        slurm: {{ include "slurm-cluster-storage.volume.jail.mount" . }}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
        - name: mount-jail-glusterfs
          image: ubuntu:focal
          command:
            - /bin/sh
            - -c
            - /mount-scripts/ensure_mounted_glusterfs.sh -g {{ include "slurm-cluster-storage.volume.jail.hostname" . }} -p /mnt/jail -s 60
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-mount
              mountPath: /host/mnt
              mountPropagation: Bidirectional
            - name: mount-scripts
              mountPath: /mount-scripts
      volumes:
        - name: host-mount
          hostPath:
            path: /mnt
        - name: mount-scripts
          configMap:
            name: mount-scripts
            defaultMode: 0500
      tolerations:
        # Allow scheduling on GPU nodes
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              # Require scheduling on GPU nodes
              - matchExpressions:
                  - key: nebius.com/node-group-id
                    operator: In
                    values:
                      - {{ include "slurm-cluster-storage.nodeGroup.gpu" . }}
                      # Require scheduling on Non-GPU nodes
              - matchExpressions:
                  - key: nebius.com/node-group-id
                    operator: In
                    values:
                      - {{ include "slurm-cluster-storage.nodeGroup.nonGpu" . }}
{{- end }}

