{{- range .Values.volume.jailSubMounts }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "slurm-cluster-storage.volume.jail-submount.pv" . }}
spec:
  storageClassName: {{ include "slurm-cluster-storage.volume.jail-submount.storageClass" $ }}
  volumeMode: Filesystem
  mountOptions:
    - rw
    - relatime
    - exec
  capacity:
    storage: {{ include "slurm-cluster-storage.volume.jail-submount.size" . }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/{{ include "slurm-cluster-storage.volume.jail-submount.name" . }}
  claimRef:
    namespace: {{ $.Release.Namespace }}
    name: {{ include "slurm-cluster-storage.volume.jail-submount.pvc" . }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
{{ $.Values.scheduling.cpuAndGpu.matchExpressions | toYaml | indent 12 }}
---
{{- end }}
