apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "slurm-cluster-storage.volume.jail.pv" . }}
spec:
  storageClassName: {{ include "slurm-cluster-storage.volume.jail.storageClass" . }}
  volumeMode: Filesystem
  mountOptions:
    - rw
    - relatime
    - exec
    - dev
  capacity:
    storage: {{ include "slurm-cluster-storage.volume.jail.size" . }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/jail
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ include "slurm-cluster-storage.volume.jail.pvc" . }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
{{ .Values.scheduling.cpuAndGpu.matchExpressions | toYaml | indent 12 }}
