{{- range .Values.volume.jailSubMounts }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "slurm-cluster-storage.volume.jail-submount.mount" . }}
spec:
  selector:
    matchLabels:
      slurm: {{ include "slurm-cluster-storage.volume.jail-submount.mount" . }}
  template:
    metadata:
      labels:
        slurm: {{ include "slurm-cluster-storage.volume.jail-submount.mount" . }}
    spec:
      containers:
        - name: mount-jail-submount-filestore
          image: busybox
          command:
            - /bin/sh
            - -c
            - /mount-scripts/ensure_mounted_filestore.sh -d {{ include "slurm-cluster-storage.volume.jail-submount.device" . }} -p /mnt/{{ include "slurm-cluster-storage.volume.jail-submount.name" . }} -s 60
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-mount
              mountPath: /host/mnt
              mountPropagation: Bidirectional
            - name: mount-scripts
              mountPath: /mount-scripts
      volumes:
        - name: host-mount
          hostPath:
            path: /mnt
        - name: mount-scripts
          configMap:
            name: mount-scripts
            defaultMode: 0500
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
{{ $.Values.scheduling.cpuAndGpu.matchExpressions | toYaml | indent 18 }}
      tolerations:
{{ $.Values.scheduling.cpuAndGpu.tolerations | toYaml | indent 8}}
---
{{- end }}
