apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/helm-cert-manager.yaml
  - ../../base/helm-prometheus-stack.yaml
  - ../../base/helm-slurm-cluster.yaml
  - ../../base/helm-slurm-monitor.yaml
  - ../../base/helm-soperator.yaml
  - ../../base/helm-victoriametrics.yaml
  - ../../base/repo-bedag.yaml
  - ../../base/repo-cert-manager.yaml
  - ../../base/repo-prometheus-stack.yaml
  - ../../base/repo-soperator.yaml
  - ../../base/repo-victoriametrics.yaml
  - ./pv.yaml
configMapGenerator:
  - name: slurm-vars
    namespace: flux-system
    files:
      - values.yaml=slurm-vars.yaml
    options:
      disableNameSuffixHash: true
patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmRepository
      name: soperator
    path: ./patch.yaml
