---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters/finalizers
  verbs:
  - update
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters/status
  verbs:
  - get
  - patch
  - update
