# permissions for end users to view slurmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: slurmcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slurm-operator
    app.kubernetes.io/part-of: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: slurmcluster-viewer-role
rules:
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters/status
  verbs:
  - get
