# permissions for end users to edit slurmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: slurmcluster-editor-role
rules:
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters/status
  verbs:
  - get
