{{- range .Values.volume.jailSubMounts }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "slurm-cluster-filestore.volume.jail-submount.pv" . }}
spec:
  storageClassName: {{ include "slurm-cluster-filestore.volume.jail-submount.storageClass" $ }}
  volumeMode: Filesystem
  mountOptions:
    - rw
    - relatime
    - exec
  capacity:
    storage: {{ include "slurm-cluster-filestore.volume.jail-submount.size" . }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/{{ include "slurm-cluster-filestore.volume.jail-submount.name" . }}
  claimRef:
    namespace: {{ $.Release.Namespace }}
    name: {{ include "slurm-cluster-filestore.volume.jail-submount.pvc" . }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        # Allow attaching to GPU nodes
        - matchExpressions:
            - key: nebius.com/node-group-id
              operator: In
              values:
                - {{ include "slurm-cluster-filestore.nodeGroup.gpu" $ }}
                # Allow attaching to Non-GPU nodes
        - matchExpressions:
            - key: nebius.com/node-group-id
              operator: In
              values:
                - {{ include "slurm-cluster-filestore.nodeGroup.nonGpu" $ }}
{{- end }}
