apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "slurm-cluster-filestore.class.local.name" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
