apiVersion: slurm.nebius.ai/v1
kind: SlurmCluster
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "slurm-cluster.name" . }}
  {{- with include "slurm-cluster.labels" . }}
  labels:
    {{- . | nindent 4 -}}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- .  | toYaml | nindent 4 }}
  {{- end }}
spec:
  crVersion: {{ .Chart.Version }}
  pause: {{ .Values.pause }}
  k8sNodeFilters:
    {{- range .Values.k8sNodeFilters }}
    - name: {{ .name }}
    {{- with .affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- end }}
  volumeSources:
    {{- range .Values.volumeSources }}
    - name: {{ .name | quote }}
      {{- omit . "name" | toYaml | nindent 6 }}
    {{- end }}
  secrets:
    mungeKey:
      name: {{ include "slurm-cluster.secret.mungeKey.name" . }}
      key: {{ include "slurm-cluster.secret.mungeKey.key" . }}
  populateJail:
    image: {{ include "slurm-cluster.image.populateJail" . }}
    k8sNodeFilterName: {{ required "Populate Jail job k8s node filter name must be provided." .Values.populateJail.k8sNodeFilterName | quote }}
    {{- if .Values.populateJail.jailSnapshotVolume }}
    jailSnapshotVolume:
      volumeSourceName: {{ required "Jail snapshot volume source name must be provided." .Values.populateJail.jailSnapshotVolume.volumeSourceName | quote }}
    {{- end }}
  periodicChecks:
    ncclBenchmark:
      enabled: {{ required "NCCL benchmark enabled flag must be provided." .Values.periodicChecks.ncclBenchmark.enabled }}
      schedule: {{ (default "0 */3 * * *" .Values.periodicChecks.ncclBenchmark.schedule) | quote }}
      activeDeadlineSeconds: {{ default 1800 .Values.periodicChecks.ncclBenchmark.activeDeadlineSeconds }}
      successfulJobsHistoryLimit: {{ default 3 .Values.periodicChecks.ncclBenchmark.successfulJobsHistoryLimit }}
      failedJobsHistoryLimit: {{ default 3 .Values.periodicChecks.ncclBenchmark.failedJobsHistoryLimit }}
      image: {{ include "slurm-cluster.image.ncclBenchmark" . }}
      ncclSettings:
        minBytes: {{ (default "512Mb" .Values.periodicChecks.ncclBenchmark.ncclSettings.minBytes) | quote }}
        maxBytes: {{ (default "8Gb" .Values.periodicChecks.ncclBenchmark.ncclSettings.maxBytes) | quote }}
        stepFactor: {{ (default "2" .Values.periodicChecks.ncclBenchmark.ncclSettings.stepFactor) | quote }}
        timeout: {{ (default "20:00" .Values.periodicChecks.ncclBenchmark.ncclSettings.timeout) | quote }}
        thresholdMoreThan: {{ (default "42" .Values.periodicChecks.ncclBenchmark.ncclSettings.thresholdMoreThan) | quote }}
        useInfiniband: {{ (default false .Values.periodicChecks.ncclBenchmark.ncclSettings.useInfiniband) }}
      failureActions:
        setSlurmNodeDrainState: {{ default true .Values.periodicChecks.ncclBenchmark.failureActions.setSlurmNodeDrainState }}
      k8sNodeFilterName: {{ (required ".Values.periodicChecks.ncclBenchmark.k8sNodeFilterName must be provided." .Values.periodicChecks.ncclBenchmark.k8sNodeFilterName ) | quote }}
  slurmNodes:
    controller:
      size: {{ required ".Values.slurmNodes.controller.size must be provided." .Values.slurmNodes.controller.size }}
      k8sNodeFilterName: {{ required ".Values.slurmNodes.controller.k8sNodeFilterName must be provided." .Values.slurmNodes.controller.k8sNodeFilterName | quote }}
      slurmctld:
        image: {{ include "slurm-cluster.image.slurmctld" . }}
        port: {{ default 6817 .Values.slurmNodes.controller.slurmctld.port }}
        resources:
          cpu: {{ required ".Values.slurmNodes.controller.slurmctld.resources.cpu must be provided." .Values.slurmNodes.controller.slurmctld.resources.cpu | quote}}
          memory: {{ required ".Values.slurmNodes.controller.slurmctld.resources.memory must be provided." .Values.slurmNodes.controller.slurmctld.resources.memory | quote}}
          ephemeral-storage: {{ required ".Values.slurmNodes.controller.slurmctld.resources.ephemeralStorage must be provided." .Values.slurmNodes.controller.slurmctld.resources.ephemeralStorage | quote}}
      munge:
        image: {{ include "slurm-cluster.image.munge" . }}
        resources:
          cpu: {{ required ".Values.slurmNodes.controller.munge.resources.cpu must be provided." .Values.slurmNodes.controller.munge.resources.cpu | quote}}
          memory: {{ required ".Values.slurmNodes.controller.munge.resources.memory must be provided." .Values.slurmNodes.controller.munge.resources.memory | quote}}
          ephemeral-storage: {{ required ".Values.slurmNodes.controller.munge.resources.ephemeralStorage must be provided." .Values.slurmNodes.controller.munge.resources.ephemeralStorage | quote}}
      volumes:
        spool:
          {{- required ".Values.slurmNodes.controller.volumes.spool must be provided." .Values.slurmNodes.controller.volumes.spool | toYaml | nindent 10 }}
        jail:
          {{- required ".Values.slurmNodes.controller.volumes.jail must be provided." .Values.slurmNodes.controller.volumes.jail | toYaml | nindent 10 }}
    worker:
      size: {{ required ".Values.slurmNodes.worker.size must be provided." .Values.slurmNodes.worker.size }}
      k8sNodeFilterName: {{ required ".Values.slurmNodes.worker.k8sNodeFilterName must be provided." .Values.slurmNodes.worker.k8sNodeFilterName | quote }}
      slurmd:
        image: {{ include "slurm-cluster.image.slurmd" . }}
        port: {{ default 6818 .Values.slurmNodes.worker.slurmd.port }}
        resources:
          cpu: {{ required ".Values.slurmNodes.worker.slurmd.resources.cpu must be provided." .Values.slurmNodes.worker.slurmd.resources.cpu | quote}}
          memory: {{ required ".Values.slurmNodes.worker.slurmd.resources.memory must be provided." .Values.slurmNodes.worker.slurmd.resources.memory | quote}}
          ephemeral-storage: {{ required ".Values.slurmNodes.worker.slurmd.resources.ephemeralStorage must be provided." .Values.slurmNodes.worker.slurmd.resources.ephemeralStorage | quote}}
          nvidia.com/gpu: {{ required ".Values.slurmNodes.worker.slurmd.resources.gpu must be provided." .Values.slurmNodes.worker.slurmd.resources.gpu | quote }}
      munge:
        image: {{ include "slurm-cluster.image.munge" . }}
        resources:
          cpu: {{ required ".Values.slurmNodes.worker.munge.resources.cpu must be provided." .Values.slurmNodes.worker.munge.resources.cpu | quote}}
          memory: {{ required ".Values.slurmNodes.worker.munge.resources.memory must be provided." .Values.slurmNodes.worker.munge.resources.memory | quote}}
          ephemeral-storage: {{ required ".Values.slurmNodes.worker.munge.resources.ephemeralStorage must be provided." .Values.slurmNodes.worker.munge.resources.ephemeralStorage | quote}}
      volumes:
        spool:
          {{- required ".Values.slurmNodes.worker.volumes.spool must be provided." .Values.slurmNodes.worker.volumes.spool | toYaml | nindent 10 }}
        jail:
          {{- required ".Values.slurmNodes.worker.volumes.jail must be provided." .Values.slurmNodes.worker.volumes.jail | toYaml | nindent 10 }}
        jailSubMounts:
          {{- default list .Values.slurmNodes.worker.volumes.jailSubMounts | toYaml | nindent 10 }}
    login:
      size: {{ required ".Values.slurmNodes.login.size must be provided." .Values.slurmNodes.login.size }}
      k8sNodeFilterName: {{ required ".Values.slurmNodes.login.k8sNodeFilterName must be provided." .Values.slurmNodes.login.k8sNodeFilterName | quote }}
      sshd:
        image: {{ include "slurm-cluster.image.sshd" . }}
        port: {{ default 22 .Values.slurmNodes.login.sshd.port }}
        resources:
          cpu: {{ required ".Values.slurmNodes.login.sshd.resources.cpu must be provided." .Values.slurmNodes.login.sshd.resources.cpu | quote}}
          memory: {{ required ".Values.slurmNodes.login.sshd.resources.memory must be provided." .Values.slurmNodes.login.sshd.resources.memory | quote}}
          ephemeral-storage: {{ required ".Values.slurmNodes.login.sshd.resources.ephemeralStorage must be provided." .Values.slurmNodes.login.sshd.resources.ephemeralStorage | quote}}
      sshRootPublicKeys:
        {{- default list .Values.slurmNodes.login.sshRootPublicKeys | toYaml | nindent 8 }}
      sshdServiceType: {{ default "LoadBalancer" .Values.slurmNodes.login.sshdServiceType | quote }}
      sshdServiceAnnotations:
        external-dns.alpha.kubernetes.io/hostname: "{{ include "slurm-cluster.name" . }}.slurm-operator.msp-dev.nemax.nebius.cloud."
      {{- if eq .Values.slurmNodes.login.sshdServiceType "LoadBalancer" }}
        {{- with .Values.slurmNodes.login.sshdServiceLoadBalancerIP }}
      sshdServiceLoadBalancerIP: {{ . | quote }}
        {{- end }}
      {{- end }}
      munge:
        image: {{ include "slurm-cluster.image.munge" . }}
        resources:
          cpu: {{ required ".Values.slurmNodes.login.munge.resources.cpu must be provided." .Values.slurmNodes.login.munge.resources.cpu | quote}}
          memory: {{ required ".Values.slurmNodes.login.munge.resources.memory must be provided." .Values.slurmNodes.login.munge.resources.memory | quote}}
          ephemeral-storage: {{ required ".Values.slurmNodes.login.munge.resources.ephemeralStorage must be provided." .Values.slurmNodes.login.munge.resources.ephemeralStorage | quote}}
      volumes:
        jail:
          {{- required ".Values.slurmNodes.login.volumes.jail must be provided." .Values.slurmNodes.login.volumes.jail | toYaml | nindent 10 }}
        jailSubMounts:
          {{- default list .Values.slurmNodes.login.volumes.jailSubMounts | toYaml | nindent 10 }}
