{{- if and (gt (int .Values.slurmNodes.login.size) 0) .Values.secrets.sshRootPublicKeys.create }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "slurm-cluster.secret.sshRootPublicKeys.name" . }}
type: Opaque
data:
  {{- $keys := list }}
  {{- range $index, $key := .Values.secrets.sshRootPublicKeys.keys }}
    {{- $keys = append $keys ($key | b64dec) }}
  {{- end }}
  {{- $keys = append $keys "" }}
  {{ include "slurm-cluster.secret.sshRootPublicKeys.key" . }}: {{ (join "\n"  $keys) | b64enc | quote }}
{{- end }}
