apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: slurm-dev
  name: event-creator
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-event-creator-binding
  namespace: slurm-dev
subjects:
- kind: ServiceAccount
  name: default
  namespace: slurm-dev
roleRef:
  kind: Role
  name: event-creator
  apiGroup: rbac.authorization.k8s.io