apiVersion: v1
kind: PersistentVolume
metadata:
  name: jail-poc
spec:
  storageClassName: local-pv
  volumeMode: Filesystem
  mountOptions:
    - rw
    - relatime
    - exec
    - dev
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/jail
  claimRef:
    namespace: slurm-poc
    name: jail
  nodeAffinity:
    required:
      nodeSelectorTerms:
        # Allow attaching to GPU nodes
        - matchExpressions:
            - key: nebius.com/node-group-id
              operator: In
              values:
                - f2mpmlsb2me7caebvaje
        # Allow attaching to NO-GPU nodes
        - matchExpressions:
            - key: nebius.com/node-group-id
              operator: In
              values:
                - f2misrg1i9vtg1mtcqg3
