apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: slurm-poc
  name: jail
spec:
  storageClassName: local-pv
  resources:
    requests:
      storage: 2Ti
  accessModes:
    - ReadWriteMany
